### ISSUE TITLE
Throttle Hit When Using Tool

### ISSUE THREAD

**Issue by ncc-erik-steringer** [nccgroup/PMapper#1]
**Desired Behavior:**

When running the `graph` subcommand, the tool runs and composes the graph.

 **Observed Behavior:**

When running the `graph` subcommand, the tool will dump traceback information for one of the running threads. That traceback will include some sort of exception message about hitting a limit and getting throttled. Then, the tool will not finish execution and require smashing Ctrl+C.

**Platform:**

N/A

**Suspected Root Cause:** 

An over-use of the Simulation API cause a throttle to kick in which leads to the exception being thrown.

## Help Wanted

Please confirm if you've hit this issue with a comment. If you're able to disclose the number of principals (users + roles) in your account, that will be helpful too. Additionally, if you have suggestions or information about the planned changes below, please leave a comment.

**Comment by kbroughton** [comment]
I hit this in an account with 6 users, 91 roles.
Uncommenting line 32 in util.py it seems the exception is thrown after 183 calls.
The program keeps running from there without incident.  To be clear, thousands more lines are output without triggering another exception.  On previous runs, since there was no output after the stack-trace, I ctrl+c quit, but it looks like it would have continued running and completed successfully.  I didn't watch it like a hawk, but i did not notice any significant pauses (boto has internal retry).  The run finished in ~ 2.5 hours.

The debug output shows many calls ~40 with an identical signature 
Checking if arn:aws:iam::myaccountid:user/myuser can do sts:AssumeRole
same for lambda:UpdateFunctionCode and ec2:RunInstances.  Not sure if they are duplicates or if the context_entries differ significantly.

You might try configuring the max attempts.
https://github.com/boto/botocore/pull/1260

You might also consider doing the combinatorial math to calculate/estimate how many api calls will be made, estimate the run time, keep a global counter, and add a progress bar :)

**Comment by kozmic** [comment]
@nitinitare The command you wrote tried to run the tool with a AWS profile named `graph`. You probably want to supply something as argument to `--profile`. Like:  `python pmapper.py --profile my-aws-profile graph`

**Comment by danieladams456** [comment]
I am hitting this - 685 principals.
> botocore.exceptions.ClientError: An error occurred (Throttling) when calling the SimulatePrincipalPolicy operation (reached max retries: 4): Rate exceeded

I tried using the `v1.0.0-dev` branch, but was getting a lambda error and from the last commit name about Lambda I'm assuming that is WIP.
Thank-you for your work on this tool!

**Comment by ncc-erik-steringer** [comment]
@danieladams456 , would you be willing to share the error you got from Lambda?

**Comment by danieladams456** [comment]
@ncc-erik-steringer you are referring to the dev branch, right?  I re-ran the master branch script and it got past the rate limit.  Would you like me to open that as a separate issue or put it here?
Thanks.

**Comment by ncc-erik-steringer** [comment]
@danieladams456 , separate issue would be great!

**Comment by ncc-erik-steringer** [comment]
Resolved in https://github.com/nccgroup/PMapper/releases/tag/v1.0.0 by avoiding the simulation API. Closing.
