### ISSUE TITLE
Multi-Threaded & Netwrok - Recommendations

### ISSUE THREAD

**Issue by 2009anandsingh** [nccgroup/PMapper#22]
Hello Friend,

1. Request to make it multi-threaded program and only one CPU is loaded.

2. Second onbservation - The program requires 10GB speed network speed to work in hours, other wise with below shows the stastics with different network speed with same account and same machine.

Speed - Time taken to complete
5M - 9 Hrs
10M - 7 hours
15M - 5 hrs
10 G - 2 hrs

Requires improvement on network.

Rest all, we were happy running the program. Great work.

Regards,
Anand

**Comment by ncc-erik-steringer** [comment]
Hi there,

v1.0.0 is now released: https://github.com/nccgroup/PMapper/releases/tag/v1.0.0

It makes a massive speed improvement by performing all authorization checks locally (instead of calling the Simulation API), which I believe was the main bottleneck. Please let me know if you see an improvement or otherwise.
